services:
  docs:
    image: meteor_template_local_docs
    container_name: meteor_template_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./meteor_template:/app/meteor_template:z
    ports:
      - '9000:9000'
    command: /start-docs
